version: "3.3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.dockerfile
    ports:
      - 8090:80
    links:
      - fpm
    volumes:
      - ./:/var/www/bike-shop
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.dockerfile
    volumes:
      - ./:/var/www/bike-shop
  mysql:
    image: mysql:8.0
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop